/**
 * xAI Work Storage - Stores work output generated by xAI Agent
 */

import type Database from "better-sqlite3";
import { nanoid } from "nanoid";

// =============================================================================
// TYPES
// =============================================================================

export type XaiWorkStatus = 'PENDING' | 'IN_PROGRESS' | 'COMPLETED' | 'FAILED';

export interface XaiWork {
  id: string;
  jobId: string;
  status: XaiWorkStatus;
  /** The work output produced by xAI */
  output: string | null;
  /** Any artifacts/deliverables (JSON array of URLs or content) */
  artifacts: string[];
  /** Execution notes/logs from xAI */
  executionNotes: string | null;
  /** Error message if failed */
  errorMessage: string | null;
  /** Processing started at */
  startedAt: string | null;
  /** Processing completed at */
  completedAt: string | null;
  createdAt: string;
}

export interface XaiWorkRow {
  id: string;
  job_id: string;
  status: string;
  output: string | null;
  artifacts: string; // JSON stringified array
  execution_notes: string | null;
  error_message: string | null;
  started_at: string | null;
  completed_at: string | null;
  created_at: string;
}

// =============================================================================
// SCHEMA
// =============================================================================

export const XAI_WORK_SCHEMA = `
-- xAI Work Results table
CREATE TABLE IF NOT EXISTS xai_work (
  id TEXT PRIMARY KEY,
  job_id TEXT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
  status TEXT CHECK(status IN ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED')) DEFAULT 'PENDING',
  output TEXT,
  artifacts TEXT DEFAULT '[]',
  execution_notes TEXT,
  error_message TEXT,
  started_at TEXT,
  completed_at TEXT,
  created_at TEXT NOT NULL
);

-- Index for fast job lookup
CREATE INDEX IF NOT EXISTS idx_xai_work_job ON xai_work(job_id);
CREATE INDEX IF NOT EXISTS idx_xai_work_status ON xai_work(status);
`;

// =============================================================================
// ROW CONVERSION
// =============================================================================

function rowToXaiWork(row: XaiWorkRow): XaiWork {
  return {
    id: row.id,
    jobId: row.job_id,
    status: row.status as XaiWorkStatus,
    output: row.output,
    artifacts: JSON.parse(row.artifacts || '[]'),
    executionNotes: row.execution_notes,
    errorMessage: row.error_message,
    startedAt: row.started_at,
    completedAt: row.completed_at,
    createdAt: row.created_at,
  };
}

// =============================================================================
// CRUD OPERATIONS
// =============================================================================

/**
 * Create a new xAI work entry
 */
export function createXaiWork(
  db: Database.Database,
  jobId: string
): XaiWork {
  const id = nanoid();
  const now = new Date().toISOString();

  const stmt = db.prepare(`
    INSERT INTO xai_work (id, job_id, status, artifacts, created_at)
    VALUES (?, ?, 'PENDING', '[]', ?)
  `);

  stmt.run(id, jobId, now);

  return {
    id,
    jobId,
    status: 'PENDING',
    output: null,
    artifacts: [],
    executionNotes: null,
    errorMessage: null,
    startedAt: null,
    completedAt: null,
    createdAt: now,
  };
}

/**
 * Get xAI work by ID
 */
export function getXaiWork(
  db: Database.Database,
  id: string
): XaiWork | undefined {
  const stmt = db.prepare(`SELECT * FROM xai_work WHERE id = ?`);
  const row = stmt.get(id) as XaiWorkRow | undefined;
  return row ? rowToXaiWork(row) : undefined;
}

/**
 * Get xAI work by job ID
 */
export function getXaiWorkByJob(
  db: Database.Database,
  jobId: string
): XaiWork | undefined {
  const stmt = db.prepare(`
    SELECT * FROM xai_work 
    WHERE job_id = ? 
    ORDER BY created_at DESC 
    LIMIT 1
  `);
  const row = stmt.get(jobId) as XaiWorkRow | undefined;
  return row ? rowToXaiWork(row) : undefined;
}

/**
 * Update xAI work status
 */
export function updateXaiWorkStatus(
  db: Database.Database,
  id: string,
  status: XaiWorkStatus
): void {
  const updates: string[] = ['status = ?'];
  const values: any[] = [status];

  if (status === 'IN_PROGRESS') {
    updates.push('started_at = ?');
    values.push(new Date().toISOString());
  } else if (status === 'COMPLETED' || status === 'FAILED') {
    updates.push('completed_at = ?');
    values.push(new Date().toISOString());
  }

  values.push(id);

  const stmt = db.prepare(`
    UPDATE xai_work 
    SET ${updates.join(', ')}
    WHERE id = ?
  `);
  stmt.run(...values);
}

/**
 * Save xAI work output
 */
export function saveXaiWorkOutput(
  db: Database.Database,
  id: string,
  output: string,
  artifacts?: string[],
  executionNotes?: string
): void {
  const stmt = db.prepare(`
    UPDATE xai_work 
    SET output = ?, 
        artifacts = ?, 
        execution_notes = ?,
        status = 'COMPLETED',
        completed_at = ?
    WHERE id = ?
  `);
  stmt.run(
    output,
    JSON.stringify(artifacts || []),
    executionNotes || null,
    new Date().toISOString(),
    id
  );
}

/**
 * Save xAI work error
 */
export function saveXaiWorkError(
  db: Database.Database,
  id: string,
  errorMessage: string
): void {
  const stmt = db.prepare(`
    UPDATE xai_work 
    SET error_message = ?,
        status = 'FAILED',
        completed_at = ?
    WHERE id = ?
  `);
  stmt.run(errorMessage, new Date().toISOString(), id);
}

/**
 * List pending xAI work
 */
export function listPendingXaiWork(
  db: Database.Database,
  limit = 50
): XaiWork[] {
  const stmt = db.prepare(`
    SELECT * FROM xai_work 
    WHERE status = 'PENDING' 
    ORDER BY created_at ASC 
    LIMIT ?
  `);
  const rows = stmt.all(limit) as XaiWorkRow[];
  return rows.map(rowToXaiWork);
}
